services:
  app:
    build: .
    container_name: launchpad-app
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5173